### ISSUE TITLE
Design RDB feature relating traits

### ISSUE THREAD

**Issue by yanganto** [second-state/SewUp#12]
It is good for developers to design a table schema and implement CRUD handler in quick way
```rust
#[derive(EwasmTable)]
struct Person {
    // id: u32
    trusted: bool,
    age: u8,
}

#[derive(EwasmTable)]
#[ewasm_belongs_to(Person)]
pub struct Post {
    //id: u32,
    person_id: i32,
    url: Raw,
}

#[ewasm_main]
fn main() -> Result<()> {
    let contract = Contract::new()?;
    match contract.get_function_selector()? {
        // short cut for record handles
        ewasm_crud!(Person),

        // record handles
        ewasm_get!(Person),
        ewasm_create!(Person),
        ewasm_update!(Person),
        ewasm_delete!(Person),

        // table handles
        ewasm_count!(Person)
        ewasm_drop!(Person)
        _ => return Err(Error::UnknownHandle.into()),
    };

    Ok(())
}
```

# Items
- [ ] Implement `EwasmTable` and make sure the struct is Sized #77 
- [ ] Implement basic CRUD handler for a sized schema #76 
- [ ] Implement simple relations `#[ewasm_belongs_to(TableName)]` #78
- [ ] Execute sql command in handler #79
- [ ] Version lock feature for table #80
- [ ] Handle many-to-many relationship #81
